// Graphs
export const GET_GRAPH_SUCCESS = 'GET_GRAPH_SUCCESS';
export const LAYOUT_SELECT_CHANGE = 'LAYOUT_SELECT_CHANGE';
export const VISIBILITY_CHECKBOX_CHANGE = 'VISIBILITY_CHECKBOX_CHANGE';
export const TAGS_SELECT_CHANGE = 'TAGS_SELECT_CHANGE';
