// main
export const SEND_REMOTE_REQUEST = 'SEND_REMOTE_REQUEST';
export const GET_REMOTE_ERROR = 'GET_REMOTE_ERROR';

// Graphs
// export const GET_GRAPH_REQUEST = 'GET_GRAPH_REQUEST';
export const GET_GRAPH_SUCCESS = 'GET_GRAPH_SUCCESS';
// export const GET_GRAPH_ERROR = 'GET_GRAPH_ERROR';
export const LAYOUT_SELECT_CHANGE = 'LAYOUT_SELECT_CHANGE';
export const VISIBILITY_CHECKBOX_CHANGE = 'VISIBILITY_CHECKBOX_CHANGE';
export const DEPTH_CHECKBOX_CHANGE = 'DEPTH_CHECKBOX_CHANGE';
export const TAGS_SELECT_CHANGE = 'TAGS_SELECT_CHANGE';
export const OPEN_DETAILS_PANEL = 'OPEN_DETAILS_PANEL';
export const CLOSE_DETAILS_PANEL = 'CLOSE_DETAILS_PANEL';
export const TAGS_VISIBILITY_CHECKBOX_CHANGE = 'TAGS_VISIBILITY_CHECKBOX_CHANGE';

// Databases (ex BioDBCore)
export const GET_DATABASE_REQUEST = 'GET_DATABASE_REQUEST';
export const GET_DATABASE_SUCCESS = 'GET_DATABASE_SUCCESS';
export const GET_DATABASE_ERROR = 'GET_DATABASE_ERROR';
